{% set name = "gotrue" %}
{% set version = "2.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9ced242b16c6d6bedc43bca21bbefea1ba5fb35fcdaad7d529342099d3b1767

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}
    - httpx >=0.26,<0.29
    - pydantic >=1.10,<3

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - gotrue

about:
  home: https://github.com/supabase-community/gotrue-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python client implementation of Supabase's GoTrue
  description: |
    Python client implementation of Supabase's GoTrue

extra:
  recipe-maintainers:
    - timkpaine
    - J0
    - anand2312
